import Head from 'next/head';
import Image from 'next/image';
import Header from '@components/Header';
import Footer from '@components/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Friendzine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header>
        <h1 className={styles.title}>Friendzine</h1>
      </Header>

      <main className={styles.main}></main>

      <Footer />
    </div>
  );
}
